atom/language-sass

settings/language-sass.cson

With the following snippet in a sass file, the cursor positioned at the end of `back`, the completion never provides the properties names: 
```sass
body 
back
```
Autocomplete and Autocomplete+ both use the `editor.completion` field from the package settings, which use the following selector `.source.sass .meta.property-list` for sass completion of properties name. 
Sadly, there's no `property-list` class when typing a property in a selector, instead the grammar use `.meta.selector.css` when typing the beginning of a property name.
I'm not sure if replacing `.source.sass .meta.property-list` by `.source.sass .meta.selector` in the setting is the right way of solving that issue. If you think we can solve it like that I can take care of creating a PR  for that.
cc/ @kevinsawicki

SASS completion selector setting doesn't match how the grammar tokenize the buffer

---

snippets/language-sass.cson

The CSS performance of `background` over `background-color` seems like a valid argument.
Fixes #13.

Expand background to background, not background-image

---

grammars/scss.cson

- `to` is also a keyword in `@for` ([source](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#_10))
- most other at-rules are highlighted as soon as their written, so now `@font-face` does the same

Small patches

---

grammars/scss.cson

It's pretty much the same as `@warn` except `@error` does throw.
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#_7

Add support for the `@error` directive

---

grammars/sass.cson
grammars/scss.cson
spec/sass-spec.coffee

Current the `:` for variable setting is only parsed as `punctuation`.
This PR update the scope of `:` for sass and scss. It also adds `.scss` to scss grammar.

Update variable setting scope

---

grammars/scss.cson
spec/scss-spec.coffee

Looks like it may have just been accidentally removed or forgotten, as the capture group was already there.
Fixes #39

Tokenize closing attribute-selector bracket

---

grammars/sass.cson
spec/sass-spec.coffee

Because Sass is a whitespace-sensitive language...
Fixes #98

Tokenize indented variables in Sass

---

grammars/scss.cson
spec/scss-spec.coffee

~~Fixes #102~~
This PR just fixes general comment highlighting in variables.  See #114 for the real fix for maps.

Tokenize comments in variables

---

grammars/scss.cson
spec/scss-spec.coffee

Preserves compatibility with autocomplete-css.
This is only temporary until I merge the rest of the language-sass PRs that are open.  I took a look at autocomplete-css and have some ideas for improving its scope matching, though that requires changes to other CSS language packages and so is well outside the scope of just updating language-sass.

Revert tokenization change for attribute classes

---

grammars/scss.cson
spec/scss-spec.coffee

In addition:
* Fixed closing brackets not being tokenized after nested selectors
* Fixed overeager `property-value` scope.  It no longer matches the colon and whitespace after the property name, nor the semicolon after the value.
Fixes #74
Fixes #79

Tokenize nested property lists

---

grammars/scss.cson
spec/scss-spec.coffee

This PR made me realize how horrible the scopes for language-sass currently are.  `punctuation.definition`, seriously?
Anyway, fixes #56

Tokenize parentheses within function parameters

---

grammars/scss.cson
spec/scss-spec.coffee

Part of the problem is that the first block in [this example](https://github.com/atom/language-sass/issues/70#issuecomment-118499932) is also getting tokenized as a property list.  That hasn't been fixed, but at least it won't affect `nth-child` highlighting now.
Fixes #70

Give nth-* pseudo-classes their own capture regex

---

settings/language-sass.cson

Basically, auto-indent if:
* the line does not contain a colon
OR
* the line is a pseudo-class/element
OR
* the line is an at-rule
This is my first time writing auto-indentation regexes.  Things might not work as expected.
Fixes #95
/cc @johnburkhard, @serhiicss

Add Sass auto-indentation rules

---

grammars/scss.cson
spec/scss-spec.coffee

Rewrite #at_rule_include

---

grammars/scss.cson
spec/scss-spec.coffee

Tokenize `:` as part of a pseudo-class

---

grammars/scss.cson
spec/scss-spec.coffee

Improve the support for @keyframes

---

grammars/scss.cson

Add syntax highlighting for `scss.liquid`. Useful for Shopify theme development, etc.

Highlighting for scss.liquid

---

grammars/scss.cson
spec/scss-spec.coffee

As for [less](https://github.com/atom/language-less/pull/71), same for scss.
The patch adds support for css variables (properties starting with --) and gives them the same scope as scss variables (`variable.scss`).
```css
:root {
--spacing-unit: 6px;
--cell-padding: (4 * var(--spacing-unit));
}
```
Only fixes the issue for SCSS. (I don't know if it is also an issue in SASS)
A different scope could be considered for SCSS , such as `variable.css`, matching the scope that the language-css grammar uses
Correct coloring of css variables in SCSS.

Support CSS variables

---

grammars/scss.cson
spec/scss-spec.coffee

Simple change to add comments to media queries.
None.
Comments in media queries will be highlighted.
None.
Fixes #177

Add comment support to media queries

---

grammars/scss.cson
spec/scss-spec.coffee

This PR removes specific regexes that were designed to capture numbers in rgb functions.  The benefit of this is minimal, and the regex is also prone to capturing false positives since it did a negative lookbehind for a specific number of functions that also used three numbers.  Unfortunately, since the number of functions is always growing, this was a rather ineffective measure.
The regex could have been changed to use a _positive_ lookbehind, but I think that the very minimal benefits a custom rgb color capture gives over a more general numeric capture …

Remove unnecessary rgb-specific number matches

---

grammars/scss.cson
spec/scss-spec.coffee

Tokenize interpolation and escapes in selectors, update a scope to use `keyword` instead of `punctuation.separator`, and allow attribute selectors to follow a custom element.
None.
More complex selectors should receive correct highlighting instead of having "invalid" tokens everywhere.
This is a somewhat large PR, but I still don't anticipate any drawbacks.  There is a large gap in spec coverage of selectors, however.
Fixes #187
Fixes #189
Fixes #193

Tokenize interpolation and escapes in selectors

---

grammars/scss.cson
spec/scss-spec.coffee

Tokenize parentheses in property values, and as a side effect move around some of the includes so that they work properly.
Also, add property-list tokens to media queries.
None.
See above.
I don't think there will be any.
Fixes #194

Allow parentheses in property values

---

.coffeelintignore
grammars/sass.cson
grammars/scss.cson
spec/sass-spec.coffee
spec/scss-spec.coffee

See atom/language-less#73. This PR links the package with `language-css` so Sass, Less and CSS all share the same keyword lists. No more copy+pasta.
I had to remove the [`#property_name_error`](https://github.com/atom/language-sass/blob/f992d44/grammars/scss.cson#L1155-L1188) block in order to achieve this. It doesn't even appear to be necessary, anyway.
/cc @50Wliu

Source keyword lists from CSS grammar

---

grammars/sass.cson
spec/sass-spec.coffee

Thanks to #202, I am now painfully aware of the ambiguity caused by Sass's heavy dependence on context and the near-complete lack of Sass specs (let's test for loops...but not property lists).
This PR:
1. Removes a property-list group in a match meant for selectors (introduced in #202)
2. Updates property-list meta scopes to be consistent with all the other CSS varieties
3. Updates property-list scopes to be consistent with language-css
4. Fixes colon-first property-list syntax `:color red`
5. Ensures that property values do not overpower …

Rework property-value

---

grammars/sass.cson
grammars/scss.cson
spec/sass-spec.coffee
spec/scss-spec.coffee

Uses the number regexes from language-css to avoid code duplication.
None.
Less code duplication.
Perhaps there are some small incompatibilities between CSS and SCSS number values.
None.

Inherit number matching from CSS

---

grammars/scss.cson
spec/scss-spec.coffee

Commas and semicolons now highlighted.  Meta scope changed from `meta.set.variable.scss` to `meta.definition.variable.scss` (ditto for maps) and does not include the trailing semicolon.
A separate scope could be added for the variable value, but I'm not convinced that's needed.
More accurate meta scope and highlighted punctuation.
None(?)
I'm going to say that this fixes #207 even though the values still don't have their own scope.  It's not feasible to add the list of all the font names to language-css, either.
/cc @smlombardi

Adjust variable/map scopes

---

grammars/scss.cson
spec/scss-spec.coffee

Placeholders can be in at-rules, in which case our ending lookahead wasn't matching when the at-rule was terminated after the placeholder.  Fix that.  Also fix `@extend` receiving import scopes.
None.
Placeholders will be tokenized in at-rules.
None?
Fixes #214

Tokenize placeholders in at-rules

---

grammars/sass.cson
grammars/scss.cson
spec/sass-spec.coffee
spec/scss-spec.coffee

The SCSS rules must have been removed when inheriting from language-css, but not all the rules were inherited.
N/A
Proper highlighting of pseudo-classes and elements.
No interpolation support yet.
Fixes #221

Add missing pseudo-class patterns from language-css

---

settings/language-sass.cson

Noticed this while testing out #222.  Should make life a bit easier for Sass users.
None.
Auto-indentation will occur when pressing enter after a functional pseudo-class.
None?
None

Indent after a functional pseudo-class

---

grammars/sass.cson
grammars/scss.cson
spec/sass-spec.coffee
spec/scss-spec.coffee

Sass:
* Fixed `@media`
* Only require one space for indented comments
N/A
See above
None
Part of #165

Improve Sass grammar

---

grammars/scss.cson
spec/scss-spec.coffee

Not my ideal solution, but it's simple, unlikely to regress, and it works.
Non-trivial rewrite of how interpolation is supported in selectors.
`[...$=...]` will work.
None.
Fixes #231

Tokenize $= selector

---

grammars/scss.cson
spec/scss-spec.coffee

Hi there,
This PR addresses a small issue in the scss grammar that caused property names that match selector names to be highlighted incorrectly.
The fix simply involved switching the order of the includes.
The bug can be reproduced using the current grammar by typing this into a scss file...
```scss
.foo {
color: red; // no issue
font: 'Helvetica'; // issue
cursor: pointer; // issue
content: ''; // issue
}
```
Let me know if you need anything else. Thanks so much :smile:
**Edit:**
Fixes #226

fix broken highlighting for properties sharing selector names

---

snippets/language-sass.cson

Allows the `!important` snippet to show up.

Remove duplicate .source.sass snippet selector

---

grammars/scss.cson
spec/scss-spec.coffee

Reverts atom/language-sass#234
/cc @dsifford: I'm temporarily reverting this due to #237.  Hopefully I can take a look later.
Fixes #237.

Revert "fix broken highlighting for properties sharing selector names"

---

grammars/sass.cson
grammars/sassdoc.cson
grammars/scss.cson
spec/sassdoc-spec.coffee

Adds grammar patterns for highlighting [SassDoc](http://sassdoc.com) comments, similar to how JSDoc blocks are handled in `language-javascript`.
Having docblocks highlighted makes them easier to read, and can encourage their use.

🎁 Add SassDoc grammar patterns

---

grammars/scss.cson
package.json
spec/scss-spec.js

Improve SCSS syntax highlighting, by recognizing  '-' as part of a class selector in an `@extend` statement.
Helps to properly syntax highlight class selectors when using with `@extend` in SCSS files.
none
Fixes https://github.com/atom/language-sass/issues/272

Tokenize - as a selector

---

grammars/sass.cson
grammars/scss.cson
spec/sass-spec.coffee
spec/scss-spec.coffee

Dart Sass 1.23.0 dropped recently and with it, [a new module system](http://sass.logdown.com/posts/7858341-the-module-system-is-launched).
This pull request adds grammar for:
- [`@use`](https://sass-lang.com/documentation/at-rules/use)
- [`@forward`](https://sass-lang.com/documentation/at-rules/forward)
- `module.$variables`
- `module.functions()`
- `@include module.includes()`
Keeps the syntax highlighting for SASS and SCSS files relevant.
- Motivated from microsoft/vscode#81943 since they seem to use the grammar files here.
- Closes #270

SASS Modules (@use and @forward)
